### ISSUE TITLE
Can't add images to an existing slider

### ISSUE THREAD

**Issue by lancesnider** [enupal/slider#9]
- Plugin version: 1.3.2 (paid, not trial)
- Craft version: 3.4

When you add a new slider, and click the button to add slides, you're able to  pick from existing images or upload new ones.

<img width="891" alt="Screen Shot 2020-06-18 at 8 01 02 PM" src="https://user-images.githubusercontent.com/3202211/85092577-cc5fc900-b19e-11ea-8cb2-d07d6176a647.png">

But when I try to edit an existing slider, the "Upload files" button is missing: 

<img width="884" alt="Screen Shot 2020-06-18 at 8 00 28 PM" src="https://user-images.githubusercontent.com/3202211/85092599-df729900-b19e-11ea-9dd3-70c669fa05de.png">

I'm not getting any errors. 

Here's what I've tried: 
- Test it on another instance of Craft
- Uninstall, reinstall the plugin
- Delete the slider and build a new one

**Comment by jzalz19** [comment]
I'm having the same issue -- it's working for a while and then after making a few changes, I'm no longer able to upload images or anything. I get that same blank window.

It's been really frustrating because my solution has just been to remake the entire slide :( I've run into it multiple times.

**Comment by lancesnider** [comment]
I ended up emailing them for support.

**Comment by jzalz19** [comment]
So I just found out it's only happening when I rename the slider after adding images to it already. The Assets Volume doesn't get renamed, so it panics and doesn't know where to look for images or where to upload them. I'm *pretty sure* this is what's going on, so I just fixed it by going to Assets and renaming the folder under Enupal Slider to match my slider.

**Comment by cherrykoda** [comment]
Confirmed this is still an issue, as explained by @jzalz19 above ^
